spring.application.name=project
spring.datasource.url=jdbc:postgresql://localhost:5432/ein_almowaten_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# This tells Hibernate to automatically create your SQL tables based on your Java code!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.web-application-type=servlet
java.awt.headless=false